### ISSUE TITLE
Items.dat Documentation

### ISSUE THREAD

**Issue by H-pun** [CLOEI/gtitem-r#1]
Just suggestion to add items.dat documentation.
Contributtion will be much appreciated 🔥

https://github.com/H-pun/growtopia-api/blob/master/docs/itemsdat.md

**Comment by CLOEI** [comment]
> Just suggestion to add items.dat documentation. Contributtion will be much appreciated 🔥
> 
> https://github.com/H-pun/growtopia-api/blob/master/docs/itemsdat.md

Nice doc! probably will update the current implementation to follow your doc.
Keep up the good work.
